/*
*	Demo of NEXUS
* 
*	Files like this will prob be generated by some sort
*	of Nexus GUI editor
*/
#include "../Engine/nexus.h"
#include "../Engine/gameObject.h"
#include "../Engine/scene.h"

int main() {
	// Create properties so Nexus knows whats up
	Nexus::GameProperties gm;
	gm.gameName = "Nexus Test";
	gm.windowHeight = 800;
	gm.windowWidth = 600;

	Nexus::Engine* engine = new Nexus::Engine(gm);

	Nexus::Scene testScene("Test Scene");

	Nexus::GameObject gameObject("Test Object");

	std::vector<Nexus::Vertex> verts = {
		{{0.0f, -0.5f}, {1.0f, 1.0f, 1.0f}},
		{{0.5f, 0.5f}, {0.0f, 1.0f, 0.0f}},
		{{-0.5f, 0.5f}, {0.0f, 0.0f, 1.0f}}
	};

	std::vector<uint16_t> inds = {
		0, 1, 2, 2, 3, 0
	};

	gameObject.mesh = new Nexus::Mesh(verts, inds);
	gameObject.loadVertShader("../shaders/vert.spv");
	gameObject.loadFragShader("../shaders/frag.spv");

	testScene.addObject(&gameObject);

	engine->InitScene(&testScene);

	while (1) {
		engine->Update(&testScene);
	}
}